### ISSUE TITLE
infinity mirroring on screen sharing

### ISSUE THREAD

**Issue by adeojoemmanuel** [AgoraIO-Community/Agora-Web-Conferencing#3]
while sharing the entire screen, there's an infinity mirror showing on the shared screen

**Comment by plutoless** [comment]
it's normal when you see your local preview of screenshare and doing screenshare at the same time. once you move to other screen the mirror disappears, you can also choose to not do preview of your screenshare

**Comment by ThangD** [comment]
@plutoless I also face the same problem. Could you pls help to share the detail solution? Thanks.
