### ISSUE TITLE
issue  npm run dev

### ISSUE THREAD

**Issue by yogesh-rinologix** [AgoraIO-Community/Agora-Web-Conferencing#5]
When i run same command 
npm run dev
following error occur :

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle agora-edu-web@5.1.0~predev: agora-edu-web@5.1.0
6 silly lifecycle agora-edu-web@5.1.0~predev: no script for predev, continuing
7 info lifecycle agora-edu-web@5.1.0~dev: agora-edu-web@5.1.0
8 verbose lifecycle agora-edu-web@5.1.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle agora-edu-web@5.1.0~dev: PATH: /usr/share/npm/bin/node-gyp-bin:/home/ecommunication/html/videoapi/demo2/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle agora-edu-web@5.1.0~dev: CWD: /home/ecommunication/html/videoapi/demo2
11 silly lifecycle agora-edu-web@5.1.0~dev: Args: [ '-c',
11 silly lifecycle   'cross-env REACT_APP_RUNTIME_PLATFORM=web react-app-rewired start' ]
12 info lifecycle agora-edu-web@5.1.0~dev: Failed to exec dev script
13 verbose stack Error: agora-edu-web@5.1.0 dev: `cross-env REACT_APP_RUNTIME_PLATFORM=web react-app-rewired start`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid agora-edu-web@5.1.0
15 verbose cwd /home/ecommunication/html/videoapi/demo2
16 error Linux 5.3.0-1023-aws
17 error argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 error node v8.10.0
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error agora-edu-web@5.1.0 dev: `cross-env REACT_APP_RUNTIME_PLATFORM=web react-app-rewired start`
24 error spawn ENOENT
25 error Failed at the agora-edu-web@5.1.0 dev script 'cross-env REACT_APP_RUNTIME_PLATFORM=web react-app-rewired start'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the agora-edu-web package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     cross-env REACT_APP_RUNTIME_PLATFORM=web react-app-rewired start
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs agora-edu-web
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls agora-edu-web
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by plutoless** [comment]
have you run npm install successfully?
